version: "3.9"
services:
  db:
    image: postgres:13
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "super secret password"
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    container_name: redis
  server:
    image: server
    container_name: server
    depends_on:
      - db
      - redis
    build:
      context: ..
      dockerfile: docker/local.dockerfile
    environment:
      - ENV_SETTINGS=local
    volumes:
      - ..:/app
    ports:
      - "8000:80"
volumes:
  postgres_data: