version: "3.9"
services:
  test-db:
    image: postgres:13
    container_name: test-db
    volumes:
      - test_postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "super secret password"
    ports:
      - "5432:5432"
    logging:
      driver: "none"
  test-redis:
    image: "redis:alpine"
    container_name: test-redis
    logging:
      driver: "none"
  test-server:
    image: test-server
    container_name: test-server
    depends_on:
      - test-db
      - test-redis
    build:
      context: ..
      dockerfile: docker/test.dockerfile
    environment:
      - ENV_SETTINGS=test
    volumes:
      - ..:/app
    ports:
      - "8000:80"
volumes:
  test_postgres_data: